services:
  database:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: youshallnotpass
      MYSQL_DATABASE: bwb
    ports:
      - "3306:3306"
    restart: always

volumes:
  database:
    driver: local
